name: Runner

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name when a job name is not provided
  cicd:
    # Name the Job
    name: CICD
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine and sets up latest Node
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '15'
          check-latest: true

      # Runs install
      - name: Install
        run: yarn

      # Runs linters
      - name: Lint
        run: yarn lint

      # Runs tests
      - name: Test
        run: yarn test
        env:
          KINGMAKER_PROJECT_ID: ${{ secrets.KINGMAKER_PROJECT_ID }}
          KINGMAKER_PRIVATE_KEY: ${{ secrets.KINGMAKER_PRIVATE_KEY }}